---
title: "Final Project"
authors: "Gwynnie Hayes and Aria Whalen"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: paper
runtime: shiny
editor_options: 
  
  chunk_output_type: console
---
```{r, warning= FALSE, echo=FALSE, message=FALSE, include = FALSE}
library(tidyverse)
library(tmap)
library(ggplot2)
library(sf)
library(maps)
library(viridis)
library(dplyr)
library(htmltools)
library(glue)
library(leaflet)
library(tigris)
library(RColorBrewer)

us_county <- map_data("county") |>
  rename(state = region) |>
  rename(county = subregion) |>
  mutate(state = str_to_title(state),
        county = str_to_title(county))


fires <- read_csv("https://raw.githubusercontent.com/gwynniehayes/gwynnie-aria/refs/heads/main/Final%20Project/final_fires.csv") |>
  mutate(percent_burned = acres/county_size_acres * 100)

states <- read_sf("https://rstudio.github.io/leaflet/json/us-states.geojson") |>
  filter(!(name %in% c("Alaska", "Hawaii", "Puerto Rico", "District of Columbia"))) |>
  select("name", "geometry") |>
  rename(state = name)

forests <- read.csv("https://raw.githubusercontent.com/gwynniehayes/SDS264/refs/heads/main/data/forests.csv") |>
  mutate('forest_cover' = forest_area/land_area * 100) 

forest_county <- read.csv("https://raw.githubusercontent.com/gwynniehayes/gwynnie-aria/refs/heads/main/Final%20Project/forest_county.csv")

forest_county_oglala <- forest_county |> 
  filter(state == "South Dakota", county == "Shannon") |>
  mutate(county = fct_recode(county, "Oglala Lakota" = "Shannon")) 


forest_county <- forest_county |> 
  mutate(county = fct_recode(county, "Okanogan" = "Okanagon",
                                     "De Baca" = "DeBaca",
                                     "Doña Ana" = "Dona Ana",
                                     "DeWitt" = "De Witt",
                                     "LaSalle" = "La Salle", 
                                     "LaPorte" = "La Porte",
                                     "LaGrange" = "Lagrange",
                                     "DeKalb" = "De Kalb",
                                     "Pleasants" = "Pleasant")) |> slice(-2384)

forest_county <- forest_county |> full_join(forest_county_oglala)

counties_sf <- counties(cb = TRUE, resolution = "5m", year = 2021) |> 
  st_transform(crs = 4326) |>
  select("NAME", "STATE_NAME", "geometry") |>
  janitor::clean_names() |>
  rename(state = state_name) |>
  rename(county = name) |>
  mutate(county = fct_recode(county, "LaSalle" = "La Salle",
                                     "DeWitt" = "De Witt"))

county_point <- read_csv("https://raw.githubusercontent.com/gwynniehayes/gwynnie-aria/refs/heads/main/Final%20Project/cfips_location.csv") |> rename(county = name)
```

So I heard you like Graphs??
======================

Inputs {.sidebar}
-------------------------
```{r, warning= FALSE, echo=FALSE, message=FALSE}
inputPanel(
  selectInput("state4", label = "Select a State",
              choices = c("None", fires$state)),
  
  selectInput("var", label = "Select a Variable",
              choices = c("% Forest Coverage" = "percent_forest_cover", 
                          "Acres Burned" = "acres", 
                          "County Size" = "county_size_acres",
                          "Percent Burned" = "percent_burned")))
```
Column
--------

```{r, warning= FALSE, echo=FALSE, message=FALSE}
renderPlot({
  fires |>
    filter(state == input$state4) |>
    ggplot(aes(y = .data[[input$var]], x = county, fill = county)) +
    geom_col(show.legend = FALSE) 
})
```

Counties and their Forests 
=======================

Inputs {.sidebar}
-------------------------
```{r, warning= FALSE, echo=FALSE, message=FALSE}
inputPanel(
  selectInput("state", label = "Select a State",
              choices = c("None", states$state)))
```

Column 
--------------------

```{r, warning= FALSE, echo=FALSE, message=FALSE}
renderPlot({
  forest_county |> full_join(us_county) |>
    filter(state == input$state) |> 
    ggplot(mapping = aes(x = long, y = lat, group = group)) + 
      geom_polygon(aes(fill = percent_forest_cover), color = "black") +
      coord_map() +
    scale_fill_viridis(option = "viridis", direction = -1) +
    theme_linedraw()
})
```

Column 
---------
```{r, warning= FALSE, echo=FALSE, message=FALSE}

ee <- 

renderPlot({
counties_sf |> left_join(forest_county) |> drop_na(percent_forest_cover) |>
    ggplot() + geom_sf(aes(fill = percent_forest_cover)) +
    scale_fill_viridis(option = "viridis", direction = -1) 
    
    
  3# ggplot(mapping = aes(x = long, y = lat, group = group)) + 
  # geom_polygon(aes(fill = percent_forest_cover), color = "black", linewidth = 0.2) + 
  # labs(fill = "% Forest Coverage", title = "Percent of Forest Coverage in each US State", x = "Longitude", y = "Latitude", caption = "Data Source: USDA Forest Service FIA Annual Report") +
  # coord_map() +
  # scale_fill_viridis(option = "viridis", direction = -1) +
  # theme_linedraw()
})
```

Fire!
===============
```{r, warning= FALSE, echo=FALSE, message=FALSE}
inputPanel(
  selectInput("state2", label = "Select a State",
              choices = c("None", fires$state)))
```

Column 
-------------
```{r, warning= FALSE, echo=FALSE, message=FALSE}
renderPlot({
  fires |> full_join(us_county) |>
    filter(state == input$state2) |>
    ggplot(mapping = aes(x = long, y = lat, group = group)) + 
      geom_polygon(aes(fill = acres), color = "black") +
      coord_map() +
    scale_fill_viridis(option = "magma", direction = -1) +
    theme_linedraw()
})
```

Column 
------------
```{r, warning= FALSE, echo=FALSE, message=FALSE}
renderPlot({
fires |> full_join(us_county) |>
  ggplot(mapping = aes(x = long, y = lat, group = group)) + 
  geom_polygon(aes(fill = acres), color = "black", linewidth = 0.2) + 
  labs(fill = "Acres Burned", title = "Acres Burned in each US County", x = "Longitude", y = "Latitude", caption = "Data Source: USDA Forest Service FIA Annual Report") +
  coord_map() +
  scale_fill_viridis(option = "magma", direction = -1) +
  theme_linedraw()
})
```

Interactive Fire!!! 
==========

```{r, warning= FALSE, echo=FALSE, message=FALSE}
inputPanel(
  selectInput("state3", label = "Select a State",
              choices = fires$state), value = "Minnesota")
```

## Interactive Maps

```{r, warning= FALSE, echo=FALSE, message=FALSE}
renderLeaflet({
    fires_sf <- fires |>
      full_join(counties_sf) |>
      filter(state == input$state3) |>
      st_as_sf()
    
    pal <- colorNumeric("Reds", domain = fires_sf$acres)

    fires_sf <- fires_sf |>
      mutate(labels = str_c(state, ": ", " in " ,county, " county ", acres, " acres burned"))

    labels <- lapply(fires_sf$labels, HTML)

    leaflet(fires_sf) |>
      setView(-97, 37.8, 4, 1) |>
      addProviderTiles("Esri.WorldTopoMap") |>
      addPolygons(
        fillColor = ~pal(acres),
        weight = 2,
        opacity = 1,
        color = "black",
        fillOpacity = 0.6,
        highlightOptions = highlightOptions(
          weight = 3,
          color = "magenta",
          fillOpacity = 0.7,
          bringToFront = TRUE),
        label = labels,
        labelOptions = labelOptions(
          style = list("font-weight" = "normal", padding = "3px 8px"),
          textsize = "12px",
          direction = "auto")
      )|>
      addScaleBar(position = "bottomleft") 
  })
```


Fire Sizes 
=============

```{r}
county_sf <- st_as_sf(county_point, coords = c("lng", "lat"))

nb.cols <- 23
mycolors <- colorFactor(
  palette = colorRampPalette(brewer.pal(8, "Dark2"), space = "Lab")(nb.cols),
  domain = county_sf$state
)
county_sf <- st_set_crs(county_sf, 4326) |>
  right_join(fires, relationship = "many-to-many") |>
  mutate(acres = acres/10000)

leaflet(county_sf) |>
      setView(-97, 37.8, 4, 1) |>
      addProviderTiles("Esri.WorldTopoMap") |>
      addCircleMarkers(data = county_sf, 
                       radius = ~acres, 
                       color = "DarkRed",
                       popup = ~paste("In ",county, " County ", round(acres * 10000), " Acres Burned."),
                       weight = 3) |> 
      addScaleBar(position = "bottomleft") 

  
```
